---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netology-deployment
  template:
    metadata:
      labels:
        app: netology-deployment
    spec:
      containers:
      - name: netology-deployment-nginx
        image: nginx:1.25.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: nginx
          containerPort: 80
      - name: netology-deployment-multitul
        image: wbitt/network-multitool:minimal
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: multitool
          containerPort: 1180
        env:
        - name: HTTP_PORT
          value: "1180"
---
apiVersion: v1
kind: Service
metadata:
  name: netology-deployment-service
spec:
  selector:
    app: netology-deployment
  type: NodePort
  ports:
  - name: nginx-svc
    port: 80
    targetPort: nginx
    nodePort: 30000
  - name: multitool-svc
    port: 1180
    targetPort: multitool
    nodePort: 30001
---
apiVersion: v1
kind: Pod
metadata:
  name: netology-deployment-pod
  labels:
    name: netology-deployment-pod
spec:
  containers:
  - name: netology-deployment-pod
    image: wbitt/network-multitool:minimal
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
