services:
  elastic:
    image: malkops/elastic:1
    volumes:
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
