---
- hosts: all
  vars:
    greet: |
      #!/bin/bash
      printf "IPs:\n$(ip -br -c a)\n"
      printf "Hostname: $(hostname)\n"
      printf "Хей, админ! Хорошего дня!"
  tasks:
    - name: Change permissions
      ansible.builtin.file:
        path: /etc/update-motd.d/
        mode: '400'
        recurse: yes
        state: directory
    - name: Change directory permissions
      ansible.builtin.file:
        path: /etc/update-motd.d
        mode: '755'
        state: touch
    - name: Create greeting
      ansible.builtin.file:
        path: /etc/update-motd.d/99-custom-greet
        mode: '755'
        state: touch
        owner: root
        group: root
    - name: Write greet
      ansible.builtin.lineinfile:
        path: /etc/update-motd.d/99-custom-greet
        line: '{{ greet }}'
