services:
  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - 3000:3000
    networks:
      - monitoring

  prometheus-server:
    image: prom/prometheus:v2.46.0
    ports:
     - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.6.1
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    ports:
     - 9100:9100  
    networks:
      - monitoring

networks:
  monitoring:
