---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-cnf-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netology-cnf-secret
  template:
    metadata:
      labels:
        app: netology-cnf-secret
    spec:
      containers:
      - name: netology-cnf-secret-nginx
        image: nginx:1.25.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: html
          mountPath: usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html
        configMap:
          name: netology-cnf-secret-nginx-simple-html
---
apiVersion: v1
kind: Service
metadata:
  name: netology-cnf-secret-service
spec:
  selector:
    app: netology-cnf-secret
  ports:
  - name: nginx-https
    port: 443
    targetPort: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netology-cnf-secret-nginx-simple-html
data:
  index.html: |
    <h1>Hello Matvey! It's a simple html page for second task</h1>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netology-cnf-secret-ingress
  labels:
    name: main-ingess
spec:
  tls:
  - hosts:
      - localhost
    secretName: netology-cnf-secret-nginx-tls
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: netology-cnf-secret-service
            port: 
              number: 443
---
apiVersion: v1
kind: Secret
metadata:
  name: netology-cnf-secret-nginx-tls
type: tls
data:
  tls.crt: |
    base63 encoded crt
  tls.key: |
    base63 encoded key
