---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-cnf-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netology-cnf-secret
  template:
    metadata:
      labels:
        app: netology-cnf-secret
    spec:
      containers:
      - name: netology-cnf-secret-nginx
        image: nginx:1.25.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: nginx
          containerPort: 80
        volumeMounts:
        - name: html
          mountPath: usr/share/nginx/html/index.html
          subPath: index.html
      - name: netology-cnf-secret-multitul
        image: wbitt/network-multitool:minimal
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: multitool
          containerPort: 1180
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx
        configMap:
          name: netology-cnf-secret-multitul-nginx-cfg
      - name: html
        configMap:
          name: netology-cnf-secret-nginx-simple-html
---
apiVersion: v1
kind: Service
metadata:
  name: netology-cnf-secret-service
spec:
  selector:
    app: netology-cnf-secret
  ports:
  - name: nginx-svc
    port: 80
    targetPort: nginx
  - name: multitool-svc
    port: 1180
    targetPort: multitool
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netology-cnf-secret-multitul-nginx-cfg
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    pid        /var/run/nginx.pid;
    error_log  /dev/stderr warn;

    events {
        worker_connections  32;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /dev/stdout  main;

        sendfile        on;

        keepalive_timeout  65;

        #gzip  on;

        server {
            listen       1180;
            server_name  localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
        }

        server {
            listen       11443    ssl;
            server_name  localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }

            ssl_certificate /certs/server.crt;
            ssl_certificate_key /certs/server.key;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netology-cnf-secret-nginx-simple-html
data:
  index.html: |
    <h1>Hello Matvey! It's a simple html page</h1>
---
apiVersion: v1
kind: Pod
metadata:
  name: netology-cnf-secret-pod
  labels:
    name: netology-cnf-secret-pod
spec:
  containers:
  - name: netology-cnf-secret-pod
    image: wbitt/network-multitool:minimal
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
