---
apiVersion: v1
kind: Service
metadata:
  name: netology-network-service
spec:
  selector:
    app: netology-network
  type: NodePort
  ports:
  - name: nginx-svc
    port: 9001
    targetPort: nginx
    nodePort: 30000
