---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-network
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netology-network
  template:
    metadata:
      labels:
        app: netology-network
    spec:
      containers:
      - name: netology-network-nginx
        image: nginx:1.25.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: nginx
          containerPort: 80
      - name: netology-network-multitul
        image: wbitt/network-multitool:minimal
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: multitool
          containerPort: 1180
        env:
        - name: HTTP_PORT
          value: "1180"
---
apiVersion: v1
kind: Service
metadata:
  name: netology-network-service
spec:
  selector:
    app: netology-network
  ports:
  - name: nginx-svc
    port: 9001
    targetPort: nginx
  - name: multitool-svc
    port: 9002
    targetPort: multitool
---
apiVersion: v1
kind: Pod
metadata:
  name: netology-network-pod
  labels:
    name: netology-network-pod
spec:
  containers:
  - name: netology-network-pod
    image: wbitt/network-multitool:minimal
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
