apiVersion: apps/v1
kind: Deployment
metadata:
  name: "malkops-netology"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    namespace: "{{ .Values.namespace | default "default" }}"
spec:
  selector:
    matchLabels:
      app: "malkops-netology"
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: "malkops-netology"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.internalPort | default "80" | int }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort | default "80" | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort | default "80" | int }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- if .Values.nginx.page }}
        volumeMounts:
        - name: html
          mountPath: usr/share/nginx/html/index.html
          subPath: index.html
        {{- end }}
      {{- if .Values.nginx.page }}
      volumes:
      - name: html
        configMap:
          name: nginx-page
      {{- end }}