apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    namespace: "{{ .Values.namespace | default "default" }}"
spec:
  type: {{ .Values.service.type | default "ClusterIP"}}
  ports:
  - port: {{ .Values.service.externalPort | default "80" }}
    targetPort: {{ .Values.service.internalPort | default "80" }}
    protocol: TCP
    name: "http"
  selector:
    app: "malkops-netology"
