{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU utility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[$__rate_interval])) by (mode) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM free GiB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$host\"} / 1073741824"
    }
   ]
  },
  {
   "title": "Disk space free GiB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"$host\", device=~\".+:\\\\\\\\134\"} / 1073741824",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "AVG CPULA 1/5/15",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$host\"}",
     "legendFormat": "1"
    },
    {
     "expr": "node_load5{instance=\"$host\"}",
     "legendFormat": "5"
    },
    {
     "expr": "node_load15{instance=\"$host\"}",
     "legendFormat": "15"
    }
   ]
  }
 ]
}