---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netology-volume
  template:
    metadata:
      labels:
        app: netology-volume
    spec:
      containers:
      - name: netology-volume-multitul
        image: wbitt/network-multitool:minimal
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: multitool
          containerPort: 1180
        env:
        - name: HTTP_PORT
          value: "1180"
        volumeMounts:
        - name: shared-file
          mountPath: /tmp/shared-log
          readOnly: true
      - name: netology-volume-busybox
        image: busybox:1.36.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        command: ['sh', '-c', 'while true; do echo `date` >> /tmp/shared-log/log; sleep 5; done']
        volumeMounts:
        - name: shared-file
          mountPath: /tmp/shared-log
      volumes:
      - name: shared-file
        emptyDir:
          sizeLimit: "50Mi"

