---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netology-volume-multitul
spec:
  selector:
    matchLabels:
      name: netology-volume-multitul
  template:
    metadata:
      labels:
        name: netology-volume-multitul
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: netology-volume-multitul
        image: wbitt/network-multitool:minimal
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: syslog
          mountPath: /var/log/node_syslog
      terminationGracePeriodSeconds: 30
      volumes:
      - name: syslog
        hostPath:
          path: /var/log/syslog


